
export const LEVELS = {

prepA: [
    "C pentascale", 
    "G pentascale", 
    "D pentascale", 
    "A min pentascale", 
    "C major triad"
],

prepB: [
    "D pentascale", 
    "A pentascale", 
    "F pentascale", 
    "E min pentascale", 
    "D min pentascale", 
    "A min (nat.) pentascale", 
    "C maj contrary motion", 
    "C maj triad", 
    "G maj triad", 
    "A min triad"
],

lvl1: [
    "C maj scale", 
    "G maj scale", 
    "F maj scale", 
    "A min natural scale", 
    "A min harmonic scale", 
    "E min natural scale", 
    "E min harmonic scale", 
    "D min natural scale", 
    "D min harmonic scale", 
    "C maj contrary motion scale", 
    "Chromatic scale starting on C", 
    "C maj triad (broken)", 
    "C maj triad (solid)", 
    "G maj triad (broken)", 
    "G maj triad (solid)", 
    "F maj triad (broken)", 
    "F maj triad (solid)", 
    "A min triad (broken)", 
    "A min triad (solid)", 
    "E min triad (broken)", 
    "E min triad (solid)", 
    "D min triad (broken)", 
    "D min triad (solid)"
],

lvl2: [
    "G maj scale", 
    "F maj scale", 
    "B♭ maj scale", 
    "E min harmonic scale", 
    "E min melodic scale", 
    "D min harmonic scale", 
    "D min melodic scale", 
    "G min harmonic scale", 
    "G min melodic scale", 
    "C maj formula pattern", 
    "G maj formula pattern", 
    "Chromatic scale starting on G", 
    "G maj triad (broken)", 
    "G maj triad (solid)", 
    "F maj triad (broken)", 
    "F maj triad (solid)", 
    "B♭ maj triad (broken)", 
    "B♭ maj triad (solid)", 
    "E min triad (broken)", 
    "E min triad (solid)", 
    "D min triad (broken)", 
    "D min triad (solid)", 
    "G min triad (broken)", 
    "G min triad (solid)"
],

lvl3: [
    "D maj scale", 
    "F maj scale", 
    "B♭ maj scale", 
    "B min harmonic scale", 
    "B min melodic scale", 
    "D min harmonic scale", 
    "D min melodic scale", 
    "G min harmonic scale", 
    "G min melodic scale", 
    "D maj formula pattern", 
    "Chromatic scale starting on D", 
    "D maj triad (broken)", 
    "D maj triad (solid)", 
    "F maj triad (broken)", 
    "F maj triad (solid)", 
    "B♭ maj triad (broken)", 
    "B♭ maj triad (solid)", 
    "B min triad (broken)", 
    "B min triad (solid)", 
    "D min triad (broken)", 
    "D min triad (solid)", 
    "G min triad (broken)", 
    "G min triad (solid)"
],

lvl4: [
    "D maj scale", 
    "A maj scale", 
    "B♭ maj scale", 
    "E♭ maj scale", 
    "B min harmonic scale", 
    "B min melodic scale", 
    "G min harmonic scale", 
    "G min melodic scale", 
    "C min harmonic scale", 
    "C min melodic scale", 
    "C min harmonic formula pattern", 
    "Chromatic scale starting on C", 
    "D maj triad (broken)", 
    "D maj triad (solid)", 
    "A maj triad (broken)", 
    "A maj triad (solid)", 
    "B♭ maj triad (broken)", 
    "B♭ maj triad (solid)", 
    "E♭ maj triad (broken)", 
    "E♭ maj triad (solid)", 
    "B min triad (broken)", 
    "B min triad (solid)", 
    "G min triad (broken)", 
    "G min triad (solid)", 
    "C min triad (broken)", 
    "G min triad (solid)" 
],

lvl5: [
    "A maj scale", 
    "E maj scale", 
    "F maj scale", 
    "A♭ maj scale", 
    "A min harmonic scale", 
    "A min melodic scale", 
    "E min harmonic scale", 
    "E min melodic scale", 
    "F min harmonic scale", 
    "F min melodic scale", 
    "A maj formula pattern", 
    "A min harmonic formula pattern", 
    "Chromatic scale starting on A", 
    "Chromatic scale starting on F", 
    "A maj triad (broken)", 
    "A maj triad (solid)", 
    "E maj triad (broken)", 
    "E maj triad (solid)", 
    "F maj triad (broken)", 
    "F maj triad (solid)", 
    "A♭ maj triad (broken)", 
    "A♭ maj triad (solid)", 
    "A min triad (broken)", 
    "A min triad (solid)", 
    "E min triad (broken)", 
    "E min triad (solid)", 
    "F min triad (broken)", 
    "F min triad (solid)"
],

lvl6: [
    "G maj scale", 
    "E maj scale", 
    "B maj scale", 
    "D♭ maj scale", 
    "G min harmonic scale", 
    "G min melodic scale", 
    "E min harmonic scale", 
    "E min melodic scale", 
    "B min harmonic scale", 
    "B min melodic scale", 
    "C♯ min harmonic scale", 
    "C♯ min melodic scale", 
    "E maj formula pattern", 
    "E min harmonic formula pattern", 
    "Chromatic scale starting on E", 
    "Chromatic scale starting on D♭", 
    "G maj triad (broken)", 
    "G maj triad (solid)", 
    "E maj triad (broken)", 
    "E maj triad (solid)", 
    "B maj triad (broken)", 
    "B maj triad (solid)", 
    "D♭ maj triad (broken)", 
    "D♭ maj triad (solid)", 
    "G min triad (broken)", 
    "G min triad (solid)", 
    "E min triad (broken)", 
    "E min triad (solid)", 
    "B min triad (broken)", 
    "B min triad (solid)", 
    "C♯ min triad (broken)", 
    "C♯ min triad (solid)", 
    "G dom 7th chord", 
    "E dom 7th chord", 
    "B dom 7th chord", 
    "D♭ dom 7th chord", 
    "G l. t. dim 7th chord", 
    "E l. t. dim 7th chord", 
    "B l. t. dim 7th chord", 
    "C♯ l. t. dim 7th chord", 
    "G maj arpeggios", 
    "E maj arpeggios", 
    "B maj arpeggios", 
    "D♭ maj arpeggios", 
    "G min arpeggios", 
    "E min arpeggios", 
    "B min arpeggios", 
    "C♯ min arpeggios", 
    "G dom 7th arpeggios", 
    "E dom 7th arpeggios", 
    "B dom 7th arpeggios", 
    "D♭ dom 7th arpeggios", 
    "G min dim 7th arpeggios", 
    "E min dim 7th arpeggios", 
    "B min dim 7th arpeggios", 
    "C♯ min dim 7th arpeggios"
],

lvl7: [
    "C maj scale", 
    "D maj scale", 
    "F maj scale", 
    "A♭ maj scale", 
    "G♭ maj scale", 
    "C min harmonic scale", 
    "C min melodic scale", 
    "D min harmonic scale", 
    "D min melodic scale", 
    "F min harmonic scale", 
    "F min melodic scale", 
    "G♯ min harmonic scale", 
    "G♯ min melodic scale", 
    "F♯ min harmonic scale", 
    "F♯ min melodic scale", 
    "D maj formula pattern", 
    "E min harmonic formula pattern", 
    "Chromatic scale starting on D", 
    "Chromatic scale starting on G♭", 
    "C maj 4-note chord", 
    "D maj 4-note chord", 
    "F maj 4-note chord", 
    "A♭ maj 4-note chord", 
    "G♭ maj 4-note chord", 
    "C min 4-note chord", 
    "D min 4-note chord", 
    "F maj 4-note chord", 
    "G♯ maj 4-note chord", 
    "F♯ maj 4-note chord", 
    "C dom 7th chord", 
    "D dom 7th chord", 
    "F dom 7th chord", 
    "A♭ dom 7th chord", 
    "G♭ dom 7th chord", 
    "C min l. t. dim 7th chord", 
    "D min l. t. dim 7th chord", 
    "F min l. t. dim 7th chord", 
    "G♯ min l. t. dim 7th chord", 
    "F♯ min l. t. dim 7th chord", 
    "C maj arpeggios", 
    "D maj arpeggios", 
    "F maj arpeggios", 
    "A♭ maj arpeggios", 
    "G♭ maj arpeggios", 
    "C min arpeggios", 
    "D min arpeggios", 
    "F min arpeggios", 
    "G♯ min arpeggios", 
    "C♯ min arpeggios", 
    "C dom 7th arpeggios", 
    "D dom 7th arpeggios", 
    "A♭ dom 7th arpeggios", 
    "G♭ dom 7th arpeggios", 
    "C dim 7th arpeggios", 
    "D dim 7th arpeggios", 
    "F dim 7th arpeggios", 
    "G♯ min dim 7th arpeggiois", 
    "F♯ min dim 7th arpeggios" 
],

lvl8: [
    "C maj scale", 
    "D maj scale", 
    "E maj scale", 
    "B♭ maj scale", 
    "E♭ maj scale", 
    "G♭ maj scale", 
    "C min harmonic scale", 
    "C min melodic scale", 
    "D min harmonic scale", 
    "D min melodic scale", 
    "E min harmonic scale", 
    "E min melodic scale", 
    "B♭ min harmonic scale", 
    "B♭ min melodic scale", 
    "E♭ min harmonic scale", 
    "E♭ min melodic scale", 
    "F♯ min harmonic scale", 
    "F♯ min melodic scale", 
    "E♭ maj formula pattern", 
    "E♭ min harmonic formula pattern", 
    "Chromatic scale starting on E♭", 
    "Chromatic scale starting on E", 
    "C maj 4-note chord", 
    "D maj 4-note chord", 
    "E maj 4-note chord", 
    "B♭ maj 4-note chord", 
    "E♭ maj 4-note chord", 
    "G♭ maj 4-note chord", 
    "C min 4-note chord", 
    "D min 4-note chord", 
    "E min 4-note chord", 
    "B♭ min 4-note chord", 
    "E♭ min 4-note chord", 
    "F♯ min 4-note chord", 
    "C dom 7th chord", 
    "D dom 7th chord", 
    "E dom 7th chord", 
    "B♭ dom 7th chord", 
    "G♭ dom 7th chord", 
    "C min l. t. dim 7th chord", 
    "D min l. t. dim 7th chord", 
    "E min l. t. dim 7th chord", 
    "B♭ min l. t. dim 7th chord", 
    "E♭ min l. t. dim 7th chord", 
    "F♯ min l. t. dim 7th chord", 
    "C maj arpeggios", 
    "D maj arpeggios", 
    "E maj arpeggios", 
    "B♭ maj arpeggios", 
    "E♭ maj arpeggios", 
    "G♭ maj arpeggios", 
    "C min arpeggios", 
    "D min arpeggios", 
    "E min arpeggios", 
    "B♭ min arpeggios", 
    "E♭ min arpeggios", 
    "F♯ min arpeggios", 
    "C dom 7th arpeggios", 
    "D dom 7th arpeggios", 
    "E dom 7th arpeggios", 
    "B♭ dom 7th arpeggios", 
    "E♭ dom 7th arpeggios", 
    "G♭ dom 7th arpeggios", 
    "C dim 7th arpeggios", 
    "D dim 7th arpeggios", 
    "B♭ dim 7th arpeggios", 
    "E♭ min dim 7th arpeggiois", 
    "F♯ min dim 7th arpeggios" 
]

}
